name: "\U0001F41E Bug Report"
description: Something isn't working as expected
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: Describe the unexpected behavior.
      placeholder: "e.g. The /override command fails when..."
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How can we reproduce it?
      description: If possible, share the steps to reproduce the bug.
      placeholder: "1. Run /command...\n2. See the behavior..."

  - type: markdown
    attributes:
      value: |
        📸 **Optional**: You can also attach screenshots for image detection issues.